# Copyright 2017 JanusGraph Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2
jobs:
    build-dist:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

    test-cql-diskstorage-I:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLDistributedStoreManagerTest,CQLIDAuthorityTest,CQLLockStoreTest,CQLLogTest'

    test-cql-diskstorage-II:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLMultiWriteStoreTest,CQLResultSetKeyIteratorTest,CQLStoreTest' #temporarily disabled CQLSSLStoreTest

    test-cql-graphdb-I:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLGraphCacheTest,CQLEventualGraphTest'

    test-cql-graphdb-II:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLGraphIterativeTest,CQLGraphPerformanceMemoryTest,CQLGraphTest'


    test-cql-graphdb-III:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLGraphConcurrentTest,CQLOperationCountingTest,CQLPartitionGraphTest'

    test-cql-olap:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn -q test -pl janusgraph-cql '-Dtest=CQLOLAPTest'

    test-janusgraph-test:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run tests!
            - run: mvn test -pl janusgraph-test

    test-cql-blueprints:
        docker:
            - image: circleci/openjdk:8u222-jdk-stretch
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "pom.xml" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: mvn install -DskipTests
            - save_cache:
                  paths:
                      - ~/.m2
                  key: v1-dependencies-{{ checksum "pom.xml" }}

            # run blueprints tests ONLY inside CQL module, apparently they are special tests that require -Dtest.skip.tp=false in order for them to run
            # we use -DskipTests so that all the other tests don't run, as they will already run on test-cql-diskstorage and test-cql-graphdb jobs
            - run:  mvn -q test -pl janusgraph-cql -Dtest.skip.tp=false -DskipTests
workflows:
    version: 2
    grakn-janusgraph:
        jobs:
            - test-cql-diskstorage-I
            - test-cql-diskstorage-II
            - test-cql-graphdb-I
            - test-cql-graphdb-II
            - test-cql-graphdb-III
            - test-janusgraph-test
            - test-cql-olap
#            - test-cql-blueprints Running these means running > 2400 tests - they fail after 2:50 hours - investigate
            - build-dist